server:
  port: 8083

spring:
  r2dbc:
    url: r2dbc:mysql://13.125.131.1:3306/coin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia&allowPublicKeyRetrieval=true
    username: teamthree
    password: conThree123*
    pool:
      max-size: 100
      validation-query: SELECT 1


#spring:
#  r2dbc:
#    url: r2dbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: devez105571!
#    pool:
#      max-size: 100
#      validation-query: SELECT 1
